const USERS="barbearia_clientes",CURRENT="barbearia_cliente_atual",BOOKS="barbearia_agendamentos";let screen="welcome",service="",time="",rescheduleId=null;
const read=k=>JSON.parse(localStorage.getItem(k)||"null"),write=(k,v)=>localStorage.setItem(k,JSON.stringify(v)),user=()=>read(CURRENT),screens=[...document.querySelectorAll(".screen")];
function show(n){if(n!=="register"&&n!=="welcome"&&!user())n="register";screen=n;screens.forEach(x=>x.classList.toggle("active",x.dataset.screen===n));if(n==="home")renderHome();if(n==="datetime")renderTimes();if(n==="confirm")renderSummary();if(n==="history")renderList();if(n==="profile")profileData.textContent=user()?.name+" · "+user()?.phone;location.hash=n}
document.addEventListener("click",e=>{let g=e.target.closest("[data-go]"),n=e.target.closest("[data-next]");if(g){e.preventDefault();show(g.dataset.go)}if(n){if(n.dataset.next==="datetime"&&!service)return alert("Escolha um serviço.");if(n.dataset.next==="confirm"&&!time)return alert("Escolha um horário.");show(n.dataset.next)}})
document.querySelectorAll("input[name=service]").forEach(x=>x.onchange=()=>service=x.value);
registerBtn.onclick=()=>{let name=regName.value.trim(),phone=regPhone.value.trim();if(!name||!phone)return alert("Informe nome e telefone.");let a=read(USERS)||[],u={name,phone},i=a.findIndex(x=>x.phone===phone);i>=0?a[i]=u:a.push(u);write(USERS,a);write(CURRENT,u);show("home")};
const today=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,10);date.value=today;date.min=today;
function renderHome(){let u=user();hello.textContent="Olá, "+u.name+"!";phoneLabel.textContent=u.phone}
function renderTimes(){times.replaceChildren();["09:00","10:00","11:00","13:00","14:00","15:00","16:00","17:00","18:00"].forEach(t=>{let b=document.createElement("button");b.className="time"+(t===time?" selected":"");b.textContent=t;b.onclick=()=>{time=t;renderTimes()};times.append(b)})}
function renderSummary(){summary.textContent=(rescheduleId?"Reagendar: ":"")+" "+service+" · "+date.value+" · "+time}
confirmBtn.onclick=()=>{let u=user(),a=read(BOOKS)||[];if(a.some(x=>x.date===date.value&&x.time===time&&x.status!=="cancelled"&&x.id!==rescheduleId))return alert("Este horário já está ocupado.");if(rescheduleId){let x=a.find(y=>y.id===rescheduleId);if(x){x.date=date.value;x.time=time;x.status="confirmed"}rescheduleId=null}else a.push({id:Date.now(),client:u.name,phone:u.phone,service,date:date.value,time,status:"confirmed",notifications:["whatsapp-pending","sms-pending"]});write(BOOKS,a);successSummary.textContent=service+" · "+date.value+" · "+time;show("success")};
function renderList(){let u=user(),a=(read(BOOKS)||[]).filter(x=>x.phone===u.phone),box=list;box.replaceChildren();if(!a.length){box.textContent="Nenhum agendamento.";return}a.slice().reverse().forEach(x=>{let d=document.createElement("div");d.className="appointment";d.innerHTML="<strong>"+x.service+"</strong><span>"+x.date+" · "+x.time+" · "+x.status+"</span>";if(x.status!=="cancelled"){let q=document.createElement("div");q.className="actions";let c=document.createElement("button");c.className="dark-btn";c.textContent="Cancelar";c.onclick=()=>{x.status="cancelled";write(BOOKS,read(BOOKS));renderList()};let r=document.createElement("button");r.className="gold";r.textContent="Reagendar";r.onclick=()=>{rescheduleId=x.id;service=x.service;date.value=today;time="";show("datetime")};q.append(c,r);d.append(q)}box.append(d)})}
show("welcome");