
const USERS="barbearia_clientes",CURRENT="barbearia_cliente_atual",BOOKS="barbearia_agendamentos";let current="welcome",selectedTime="",selectedService="";
const screens=[...document.querySelectorAll(".screen")],back=document.querySelector("#back");
const read=(k)=>JSON.parse(localStorage.getItem(k)||"null"),write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
function user(){return read(CURRENT)}
function show(name){if(["home","service","datetime","confirm","history","profile","contact"].includes(name)&&!user()){name="register"}current=name;screens.forEach(s=>s.classList.toggle("active",s.dataset.screen===name));back.style.visibility=name==="welcome"?"hidden":"visible";if(name==="home")renderHome();if(name==="datetime")renderTimes();if(name==="confirm")renderSummary();if(name==="history")renderList();if(name==="profile")renderProfile();location.hash=name}
function renderHome(){const u=user();if(!u)return;document.querySelector("#hello").textContent="Olá, "+u.name+"!";document.querySelector("#phoneLabel").textContent=u.phone;document.querySelector("#avatar").textContent=u.name.split(/\s+/).map(x=>x[0]).slice(0,2).join("").toUpperCase()}
function go(e){const el=e.target.closest("[data-go]");if(el){e.preventDefault();show(el.dataset.go)}}
document.addEventListener("click",e=>{go(e);const n=e.target.closest("[data-next]");if(n){e.preventDefault();if(n.dataset.next==="datetime"&&!selectedService)return alert("Escolha um serviço.");if(n.dataset.next==="confirm"&&!selectedTime)return alert("Escolha um horário.");show(n.dataset.next)}});
document.querySelectorAll(".service input").forEach(x=>x.addEventListener("change",()=>selectedService=x.value));
document.querySelector("#registerBtn").onclick=()=>{const name=document.querySelector("#regName").value.trim(),phone=document.querySelector("#regPhone").value.trim();if(!name||!phone)return alert("Informe nome e telefone.");const list=read(USERS)||[];const u={name,phone};const i=list.findIndex(x=>x.phone===phone);if(i>=0)list[i]=u;else list.push(u);write(USERS,list);write(CURRENT,u);show("home")};
back.onclick=()=>show(current==="home"?"welcome":current==="register"?"welcome":current==="service"?"home":current==="datetime"?"service":current==="confirm"?"datetime":current==="success"?"home":"home");
const date=document.querySelector("#date");date.value=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,10);date.min=date.value;
function renderTimes(){const box=document.querySelector("#times");box.replaceChildren();["09:00","10:00","11:00","13:00","14:00","15:00","16:00","17:00","18:00"].forEach(t=>{const b=document.createElement("button");b.textContent=t;b.type="button";b.className=t===selectedTime?"selected":"";b.onclick=()=>{selectedTime=t;renderTimes()};box.appendChild(b)})}
function renderSummary(){const box=document.querySelector("#summary");box.replaceChildren();const d=document.createElement("div"),b=document.createElement("b"),s=document.createElement("span");b.textContent=selectedService;s.textContent=date.value+" · "+selectedTime;d.append(b,s);box.appendChild(d)}
document.querySelector("#confirmBtn").onclick=()=>{const u=user();if(!u)return show("register");const a=read(BOOKS)||[];if(a.some(x=>x.date===date.value&&x.time===selectedTime&&x.status!=="cancelled"))return alert("Este horário já está ocupado.");const item={id:Date.now(),client:u.name,phone:u.phone,date:date.value,time:selectedTime,service:selectedService,status:"confirmed",notifications:["whatsapp-pending","sms-pending"]};a.push(item);write(BOOKS,a);document.querySelector("#successText").textContent="A confirmação foi registrada para o telefone "+u.phone+".";document.querySelector("#successSummary").textContent=selectedService+" · "+item.date+" · "+item.time;show("success")};
function renderList(){const box=document.querySelector("#list");box.replaceChildren();const u=user(),a=(read(BOOKS)||[]).filter(x=>x.phone===u.phone);if(!a.length){box.textContent="Nenhum agendamento ainda.";return}a.slice().reverse().forEach(x=>{const d=document.createElement("div");d.className="appointment";const b=document.createElement("strong"),p=document.createElement("span");b.textContent=x.service;p.textContent=x.date+" · "+x.time+" · "+x.status;d.append(b,p);box.appendChild(d)})}
function renderProfile(){const u=user();document.querySelector("#profileData").textContent=u?u.name+" · "+u.phone:""}
show("welcome");

