const KEY="barbearia_agendamentos";let current="welcome",selectedTime="",selectedService="";
const screens=[...document.querySelectorAll(".screen")],back=document.querySelector("#back");
function show(name){current=name;document.querySelector(".app").dataset.screen=name;screens.forEach(s=>s.classList.toggle("active",s.dataset.screen===name));back.style.visibility=name==="welcome"?"hidden":"visible";if(name==="datetime")renderTimes();if(name==="confirm")renderSummary();if(name==="history")renderList();location.hash=name}
document.addEventListener("click",e=>{const go=e.target.closest("[data-go]"),next=e.target.closest("[data-next]");if(go){e.preventDefault();show(go.dataset.go)}if(next){e.preventDefault();if(next.dataset.next==="datetime"&&!selectedService){alert("Escolha um serviço.");return}if(next.dataset.next==="confirm"&&!selectedTime){alert("Escolha um horário.");return}show(next.dataset.next)}});
document.querySelectorAll(".service input").forEach(x=>x.addEventListener("change",()=>selectedService=x.value));
back.onclick=()=>show(current==="home"?"welcome":current==="service"?"home":current==="datetime"?"service":current==="confirm"?"datetime":current==="success"?"home":"home");
const date=document.querySelector("#date");date.value=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,10);date.min=date.value;
function renderTimes(){const box=document.querySelector("#times");box.replaceChildren();["09:00","10:00","11:00","13:00","14:00","15:00","16:00","17:00","18:00"].forEach(t=>{const b=document.createElement("button");b.textContent=t;b.type="button";b.className=t===selectedTime?"selected":"";b.onclick=()=>{selectedTime=t;renderTimes()};box.appendChild(b)})}
function renderSummary(){document.querySelector("#summary").innerHTML="";const d=document.createElement("div");d.innerHTML="<b>"+selectedService+"</b><span>"+date.value+" · "+selectedTime+"</span>";document.querySelector("#summary").appendChild(d)}
document.querySelector("#confirmBtn").onclick=()=>{const client=document.querySelector("#client").value.trim();if(!client){alert("Informe seu nome.");return}const item={client,phone:document.querySelector("#phone").value,date:date.value,time:selectedTime,service:selectedService};const a=JSON.parse(localStorage.getItem(KEY)||"[]");if(a.some(x=>x.date===item.date&&x.time===item.time)){alert("Este horário já está ocupado.");return}a.push(item);localStorage.setItem(KEY,JSON.stringify(a));document.querySelector("#successSummary").textContent=selectedService+" · "+item.date+" · "+item.time;show("success")};
function renderList(){const box=document.querySelector("#list");box.replaceChildren();const a=JSON.parse(localStorage.getItem(KEY)||"[]");if(!a.length){box.textContent="Nenhum agendamento ainda.";return}a.slice().reverse().forEach(x=>{const d=document.createElement("div");d.className="appointment";const b=document.createElement("strong");b.textContent=x.service;const p=document.createElement("span");p.textContent=x.date+" · "+x.time+" · "+x.client;p.className="badge";d.append(b,p);box.appendChild(d)})}
show("welcome");