const API="https://barbearia-api-w37o.onrender.com/api";
const $=id=>document.getElementById(id);let csrfToken=null;
async function api(path,opt={}){const method=(opt.method||"GET").toUpperCase();const headers={"Content-Type":"application/json",...(opt.headers||{})};if(method==="POST"&&!["/owner/login","/owner/challenge","/owner/device/register"].includes(path)){if(!csrfToken)csrfToken=(await fetch(API+"/csrf",{credentials:"include"}).then(r=>r.json())).csrf_token;headers["X-CSRF-Token"]=csrfToken;}const r=await fetch(API+path,{...opt,credentials:"include",headers});const d=await r.json();if(!r.ok)throw new Error(d.error||"Erro");return d;}
const DEVICE_KEY="barbearia.owner.device.v1",DEVICE_ID_KEY="barbearia.owner.device_id.v1";let keyPair=null;
function b64u(bytes){let s="";for(const b of new Uint8Array(bytes))s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"");}
function b64uBytes(s){s=s.replace(/-/g,"+").replace(/_/g,"/");while(s.length%4)s+="=";const raw=atob(s);return Uint8Array.from(raw,c=>c.charCodeAt(0));}
function getDeviceId(){let id=localStorage.getItem(DEVICE_ID_KEY);if(!id){id=crypto.randomUUID();localStorage.setItem(DEVICE_ID_KEY,id);}return id;}
async function loadKeyPair(){if(keyPair)return keyPair;return new Promise((resolve,reject)=>{const req=indexedDB.open("barbearia-owner-device",1);req.onupgradeneeded=()=>req.result.createObjectStore("keys");req.onerror=()=>reject(req.error);req.onsuccess=()=>{const db=req.result,get=db.transaction("keys","readonly").objectStore("keys").get(DEVICE_KEY);get.onsuccess=async()=>{if(get.result){keyPair=get.result;return resolve(keyPair);}keyPair=await crypto.subtle.generateKey({name:"ECDSA",namedCurve:"P-256"},false,["sign","verify"]);const tx=db.transaction("keys","readwrite");tx.objectStore("keys").put(keyPair,DEVICE_KEY);tx.oncomplete=()=>resolve(keyPair);tx.onerror=()=>reject(tx.error);};get.onerror=()=>reject(get.error);};});}
async function publicJwk(){return crypto.subtle.exportKey("jwk",(await loadKeyPair()).publicKey);}
async function signChallenge(challenge){return b64u(await crypto.subtle.sign({name:"ECDSA",hash:"SHA-256"},(await loadKeyPair()).privateKey,b64uBytes(challenge)));}
async function authenticateOwner(phone,password){const deviceId=getDeviceId();let challenge;try{({challenge}=await api("/owner/challenge",{method:"POST",body:JSON.stringify({phone,device_id:deviceId})}));}catch(e){if(!password)throw new Error("Este dispositivo ainda não está ativado. Informe a senha de ativação.");await api("/owner/device/register",{method:"POST",body:JSON.stringify({phone,password,device_id:deviceId,public_jwk:await publicJwk()})});({challenge}=await api("/owner/challenge",{method:"POST",body:JSON.stringify({phone,device_id:deviceId})}));}return api("/owner/login",{method:"POST",body:JSON.stringify({phone,device_id:deviceId,signature:await signChallenge(challenge)})});}
$("ownerEnter").onclick=async()=>{const phone=$("ownerPhone").value.trim(),password=$("ownerPassword").value;if(!phone)return $("ownerStatus").textContent="Informe o telefone cadastrado.";try{await authenticateOwner(phone,password);$("ownerPassword").value="";$("ownerArea").hidden=false;$("ownerStatus").textContent="Dispositivo autorizado. Área privada ativa.";await render();}catch(e){$("ownerStatus").textContent=e.message;}};
async function render(){const p=await api("/owner/appointments?status=pending"),c=await api("/owner/appointments?status=confirmed"),all=await api("/owner/appointments"),users=await api("/owner/clients");$("pending").innerHTML=p.length?p.map(x=>card(x,true)).join(""):"Nenhuma solicitação pendente.";$("confirmed").innerHTML=c.length?c.map(x=>card(x,false)).join(""):"Nenhum horário confirmado.";$("clients").innerHTML=users.length?users.map(x=>'<div class="appointment"><strong>'+x.name+'</strong><span>'+x.phone+' · '+x.appointments+' agendamento(s)</span></div>').join(""):"Nenhum cliente.";$("historyOwner").innerHTML=all.filter(x=>!["pending","confirmed"].includes(x.status)).map(x=>'<div class="appointment"><strong>'+x.client+' — '+x.service+'</strong><span>'+x.date+' · '+x.time+' · '+x.status.toUpperCase()+'</span></div>').join("")||"Sem histórico.";}
function card(x,pending){let b='<div class="appointment"><strong>'+x.client+' — '+x.service+'</strong><span>'+x.date+' · '+x.time+' · '+x.phone+'</span>';if(pending)b+='<div class="actions"><button class="gold" onclick="confirmA('+x.id+')">CONFIRMAR</button><button class="dark-btn" onclick="rejectA('+x.id+')">RECUSAR</button></div>';return b+"</div>";}
async function confirmA(id){try{await api("/owner/appointments/"+id+"/confirm",{method:"POST"});await render()}catch(e){alert(e.message)}}
async function rejectA(id){try{await api("/owner/appointments/"+id+"/reject",{method:"POST"});await render()}catch(e){alert(e.message)}}
